version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: auth-go
    environment:
      POSTGRES_DB: auth-go
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
