version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: auth-go-db
    environment:
      POSTGRES_DB: auth-go
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: auth-go-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: